Support for adding services dynamically.
hyperium/tonic pull request #1408
Opened 2023-06-06 18:08 UTC by tsroka

## Motivation

This change allows more flexible creation of grpc server, specifically for use case where multiple grpc services are initiated in different parts of an application. Currently it is pretty hard to do due to Server / Router generic (and consuming value every time new svc is added).

This should also address this [issue](https://github.com/hyperium/tonic/issues/886)

## Solution

Since Routes struct does not have any generic type it can be easily used to add new services. The only complication is that it `add_service` fn is taking self by value and functions are not public. In order to make it work, RoutesBuilder was added that takes mutable reference to self and can be used to add new services, and some methods were made public. 

Please see the provided example. This change is backwards compatible.

2023-06-09 21:07 UTC, andrewhickman commented on examples/Cargo.toml
> +name = "dynanmic-server"
```suggestion
name = "dynamic-server"
```

2023-06-20 14:00 UTC, killix commented
I am looking for this feature. When can this be merged? :)

2023-06-27 18:53 UTC, tsroka commented
Hello, is there something else I need to do on my side to get it merged?

2023-07-16 00:20 UTC, killix commented
@andrewhickman any answer?

2023-07-16 08:02 UTC, andrewhickman commented
I'm not a maintainer on this repo, I don't have power to merge it

2023-07-18 22:10 UTC, killix commented
> I'm not a maintainer on this repo, I don't have power to merge it

Asked because look you are the reviewer on this PR.

2023-07-28 15:28 UTC, LucioFranco requested changes
Overall this looks really good. I would like to see a test that uses this code to ensure we don't break things down the line then we can merge this. Thanks!

2023-08-01 07:37 UTC, tsroka commented
Thanks for reviewing @LucioFranco ; added test, lmk if this is what you were looking for.

2023-08-04 14:29 UTC, tsroka commented
@LucioFranco I saw that a build is failing due to use of let else, I changed the test to use match instead, should be good now.

2023-08-13 07:36 UTC, tsroka commented
Fixed merge conflicts with master and compilation errors introduced by changes in master. @LucioFranco do you think it is ok to merge?

2023-08-25 19:14 UTC, LucioFranco approved these changes

2023-08-25 19:14 UTC, merged