Adds local_address as an option Endpoint builder.
hyperium/tonic pull request #1567
Opened 2023-11-08 21:28 UTC by jparris

## Motivation
I need to be able to set the local address to a Channel. Currently there no way to do this.

## Solution
Add `local_address` to Endpoint builder.

2025-01-15 17:11 UTC, jparris commented
@tottoto can you take a look at this PR.

2025-01-16 09:10 UTC, tottoto requested changes

2025-01-16 09:10 UTC, tottoto commented on tonic/src/transport/channel/endpoint.rs
> +    pub fn local_address(self, addr: IpAddr) -> Self {
Can this take`Option<IpAddr>` as the argument.

2025-01-16 09:10 UTC, tottoto commented on tonic/src/transport/channel/endpoint.rs
> +    /// Set the local address
```suggestion
    /// Set the local address.
```

2025-01-16 09:10 UTC, tottoto commented on tonic/src/transport/channel/endpoint.rs
> +    /// ```
As the contents of this example are all hidden, they will not be displayed. And this example itself is redundant.

```suggestion
```

2025-01-16 09:11 UTC, tottoto commented on tonic/src/transport/channel/endpoint.rs
> +    pub(crate) local_address: Option<IpAddr>,
```suggestion
    pub(crate) local_address: Option<IpAddr>,
    pub(crate) executor: SharedExec,
```

2025-01-16 21:32 UTC, jparris commented on tonic/src/transport/channel/endpoint.rs
> +    pub fn local_address(self, addr: IpAddr) -> Self {
Sure thing.

2025-01-16 22:20 UTC, tottoto approved these changes

2025-01-16 22:33 UTC, merged