Add json-codec for application/grpc+json
hyperium/tonic pull request #853
Opened 2021-12-01 14:09 UTC by zbysir

## Motivation

## Solution

2021-12-01 16:21 UTC, olix0r commented
This introduces dependencies that are only needed when this extra functionality is desired. Can it be feature-gated?

2021-12-02 01:52 UTC, zbysir commented
> This introduces dependencies that are only needed when this extra functionality is desired. Can it be feature-gated?

Good idea, I will try to add ‘feature-gated’

2021-12-02 02:22 UTC, zbysir commented
> Make json-codec be feature-gated


> This introduces dependencies that are only needed when this extra functionality is desired. Can it be feature-gated?

I did it, please review it when you have time, thank you for your help.

2021-12-07 23:03 UTC, LucioFranco requested changes
I would be happy to include this. But I think first I would like this PR to have an example and some tests. Then we can merge it.

2021-12-07 23:03 UTC, LucioFranco commented on tonic/src/codec/json.rs
> +impl<U: for<'a> serde::Deserialize<'a>> Decoder for JsonDecoder<U> {
Can we use this https://docs.rs/serde/latest/serde/de/trait.DeserializeOwned.html should be the same just a bit cleaner

2021-12-08 02:20 UTC, zbysir commented
> I would be happy to include this. But I think first I would like this PR to have an example and some tests. Then we can merge it.

Okay, I will add some tests and example later.

2021-12-16 07:38 UTC, zbysir commented
Hello?

2022-02-15 16:08 UTC, LucioFranco requested changes
Sorry for the delay. I think I would like to merge this on the condition that we add the change for build and add an example + tests (I think you added tests so that is good!).

2022-05-14 08:39 UTC, closed without merging