tonic-build: better support custom codecs
hyperium/tonic pull request #999
Opened 2022-05-04 21:05 UTC by bmwill

@LucioFranco after we chatted briefly on discord yesterday I did a bit more thinking about how improve accessibility of the code generation functionality in tonic-build. This is one potential approach. Its in a WIP state but I wanted to get your thoughts and see if this is something you'd be interested in as a contribution to tonic. If so I can spend some time actually making it usable.

## Motivation

gRPC is a general purpose RPC framework that, while generally is paired with protobuf, is agnostic to the type of serialization format used for messages and in some cases it may be desired to use a different serialization format other than protobuf. 

## Solution

This PR takes a look at one possible way to enable using a custom, non-protobuf codec for serializing messages to the wire. This is done via:
- changing the `CODEC_PATH` constant to a method which returns a `&str` for better programability
- introduces a set of builders for Services and Methods so that you can build up a service with various methods and invoke the code generation without interacting with prost or proto files. This could eventually enable developing a proc-macro that does the generation at compile time instead of needing a build script (for services which don't leverage proto files and protobuf)

2022-05-04 22:56 UTC, LucioFranco reviewed
I like this a lot! I think just need to add some docs and we can merge this. Thanks!

2022-05-04 23:03 UTC, bmwill commented on tonic-build/src/rust.rs
> +#[test]
Yeah i just whipped this together to see what you thought so now that I know you're interested i'll clean it up with docs and the like

2022-05-05 01:44 UTC, bmwill commented
Ok this should be ready for a serious review now. My main question is how you want to handle the module naming, right now its all just in a public module `rust` and nothing is reexported at the top level.

2022-05-05 14:46 UTC, LucioFranco commented
@bmwill how about `manual` instead of `rust` for the module name?

2022-05-05 15:13 UTC, LucioFranco requested changes
Overall looks great left a few comments/questions.

2022-05-05 15:13 UTC, LucioFranco commented on examples/build.rs
> +                .codec_path("crate::JsonCodec")
should we make these `crate::common` to be more clear this is tying in the types from that module file? My concern is that this build.rs is quite far from that code and crate seems a bit less obvious.

2022-05-05 15:13 UTC, LucioFranco commented on examples/src/json-codec/client.rs
> +use common::{HelloRequest, HelloResponse, JsonCodec};
We should add a module comment explaining/pointing out that the codegen comes from `build_json_codec_service` in the `build.rs` file.

2022-05-05 15:13 UTC, LucioFranco commented on examples/src/json-codec/common.rs
> +use bytes::{Buf, BufMut};
Could also use some module docs here maybe explaining what is going on. Nothing crazy is needed imo

2022-05-05 15:13 UTC, LucioFranco commented on tonic-build/src/rust.rs
> +/// Service builder.
Could use a bit more docs here

2022-05-05 15:13 UTC, LucioFranco commented on tonic-build/src/manual.rs
> +/// Service builder.
I think we should expand this doc comment to explain high level what these builders do (I don't think we need to add more to the other builders only this one).

2022-05-05 15:13 UTC, LucioFranco commented on tonic-build/src/manual.rs
> +    pub fn name<T: AsRef<str>>(mut self, name: T) -> Self {
small nit ive been using impl trait here for these types of conversions, wonder if we should switch these?

2022-05-05 15:13 UTC, LucioFranco commented on tonic-build/src/manual.rs
> +struct ServiceGenerator {
Do we actually need this extra struct? I don't mind keeping it just seems like we could just embed the code in the `compile` method?

2022-05-05 15:13 UTC, LucioFranco commented on tonic-build/src/manual.rs
> +    /// Enable or disable gRPC client code generation.
prob wanna mention the default here? (maybe we missed this also in the prost side).

2022-05-05 15:13 UTC, LucioFranco commented on examples/build.rs
> +fn build_json_codec_service() {
I think we should add a comment to point to the example here

2022-05-05 15:47 UTC, LucioFranco commented on tonic-build/src/manual.rs
> +    pub fn name<T: AsRef<str>>(mut self, name: T) -> Self {
we can keep it nbd

2022-05-05 16:16 UTC, bmwill commented
@LucioFranco Ok I've updated the PR, hopefully addressing all of your comments

2022-05-05 16:51 UTC, LucioFranco approved these changes
Thanks! LGTM

2022-05-05 16:52 UTC, merged

2022-05-07 09:06 UTC, zbysir commented
@bmwill Take a look at this: https://github.com/hyperium/tonic/issues/851, can you give me some advice? First of all thank you.

What I want most is to support multiple codecs, not a specific one.